name: CI Pipeline

on:
  push:
    branches:
      - main # Trigger on push to main branch
      - "**" # Trigger on push to any branch

jobs:
  build:
    runs-on: ubuntu-latest # The operating system to run the job on

    steps:
      - name: Download KIND
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.26.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind
      - name: Cluster Up
        run: |
          kind create cluster
