name: CI Pipeline

on:
  push:
    branches:
      - main
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.26.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          mv ./kubectl /usr/local/bin/kubectl

      - name: Cluster up
        run: |
          kind create cLuster

      - name: Test cluster access
        run: |
          kubectl cluster-info
