name: CI Pipeline

on:
  push:
    branches:
      - main
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create kind cluster
        uses: helm/kind-action@v1.12.0

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          mv ./kubectl /usr/local/bin/kubectl

      - name: Test cluster access
        run: |
          kubectl cluster-info
